import type { Metadata } from 'next';
import { Nunito, Nunito_Sans as NunitoSans } from 'next/font/google';
import './globals.css';
import { cn } from './lib/utils';

const nunito = Nunito({ subsets: ['latin'] });
const nunitoSans = NunitoSans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'antialiased min-h-screen flex flex-col',
          nunito.className,
          nunitoSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
